{{- if .Values.persistence.enabled }}
{{- $database := .Values.persistence.persistentVolumeClaim.database -}}
{{- if and (not $database.existingClaim) .Values.database.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-data-volume
  annotations:
  {{- range $key, $value := $database.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - {{ $database.accessMode }}
  resources:
    requests:
      storage: {{ $database.size }}
  {{- if $database.storageClass }}
    {{- if eq "-" $database.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $database.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- $redis := .Values.persistence.persistentVolumeClaim.redis -}}
{{- if and (not $redis.existingClaim) .Values.redis.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-volume
  annotations:
  {{- range $key, $value := $redis.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if eq .Values.persistence.resourcePolicy "keep" }}
    helm.sh/resource-policy: keep
  {{- end }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - {{ $redis.accessMode }}
  resources:
    requests:
      storage: {{ $redis.size }}
  {{- if $redis.storageClass }}
    {{- if eq "-" $redis.storageClass }}
  storageClassName: ""
    {{- else }}
  storageClassName: {{ $redis.storageClass }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
